### ISSUE TITLE
xref stream support

### ISSUE THREAD

**Issue by iamcarbon** [jdehaan/SafeRapidPdf#2]
Any plans to support xref streams?

**Comment by jdehaan** [comment]
I started investigating. I think the whole work is to decode the compressed xref stream at the beginning of the linearized pdfs.

**Comment by iamcarbon** [comment]
Same. I started trying to figure this out how to decode these and got overwhelmed reading the PDF specification. They're very common within our PDF sample set (about 1 in 8).

**Comment by jdehaan** [comment]
I struggled quite a bit with the deflate algo. I could more or less get something decoded. The shape of the outcome surprises me a bit. It's getting late here. I have to give up for now.

**Comment by jdehaan** [comment]
Initially the project was started to get PDF up to 1.4 parsed (generated by simple tools, that did not do anything fancy)... That's almost the stage the code base stayed. I would like to hive it at least at the level to be able to parse the structures properly.

**Comment by jdehaan** [comment]
I lack of time to continue seriously on the topic this week. I am digging through the spec. I think in the end by understanding properly how the xref is behaving and implementing the Deflate filter for stream this should work out already for a big bunch of PDFs.

Of course ideally I would need to implement all other algos as well... But with these two elements and a proper proxy pattern to make everything behave as if it were uncompressed this can be achieved in a reasonable amount of time.

**Comment by iamcarbon** [comment]
@jdehaan -- a quick ping to see if you had some time to work on this.

**Comment by jdehaan** [comment]
I came out of a stressful month, I'll spend some hours this weekend on that topic.

**Comment by jdehaan** [comment]
I made some progress in understanding what the predictors do and can decode the xrefstream at stream level now correctly (I checked indexes of objects manually). There are quite some tasks left over to solve: finding out the rest of the xref table automatically (I think this is part of the linearized handling) and decoding information from further streams, as the ref entries themselves can be compressed and part of streams...

**Comment by jdehaan** [comment]
I think I got it so far. Please provide me with more information if you still miss something or if it does not work as expected. I prepared some additional tooling to realize regression tests for examples you provide me with. Furthermore if you have a concrete small use case we could add that to the PdfInfoTool as well if you do not mind. The code is quite ugly, a refactoring is likely to come somewhen. Then a good set of tests is a must. Sorry for the late feedback but I am currently completely overbooked at work. I just couldn't resist taking the challenge to understand and implement (partially and in a limited way) these stream decoders! :-)

**Comment by iamcarbon** [comment]
@jdehaan This is great!

I extended the library for our use case (getting all the page info and corresponding media boxes for a file) and would be happy to contribute these changes back. 

I submitted a PR with some basic changes to minimize any future changes to start. If this looks OK, I'll follow up with a few extensions to the library that we've added to simplify getting basic PDF file info.
